baseURL: https://stat4soc.netlify.app/
languageCode: en-us
defaultContentLanguage: en
title: 林景 NUFE
theme: "cupper-hugo-theme"
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: 社会统计学教学平台 Ver.1.00
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: © 2020 - 2025 网页获[南京财经大学](http://www.nufe.edu.cn/)教改课题一般项目（编号：JGY20053）资助
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: "Jan 2, 2006"
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false
  logoAlt: "An alternative text description of the logo"
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: 简介
      url: /
      weight: 1
    - name: 目录
      url: /post/
      weight: 2
    - name: 标签
      url: /tags/
      weight: 3
    - name: 关于
      url: /about/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
